# This is a basic workflow to validate JSON file

name: JSON API Validate

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: docker://orrosenblatt/validate-json-action:latest
      env:
        # One or more relative file paths under the repository (seperated by comma) of the JSON files to validate with the schema provided.
        INPUT_SCHEMA: photos.json
        INPUT_JSONS: photos-schema.json

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: CI VM Initialized
      run: uname -a

    # Runs a single command using the runners shell
    - name: Check Paths
      run: pwd

    - name: Find Files
      run: ls -la *.json